---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/jailer --version
      register: jailer_test_output
    - debug:
        msg: '{{ jailer_test_output.stdout }}'
    - command: /usr/local/bin/firecracker --version
      register: firecracker_test_output
    - debug:
        msg: '{{ firecracker_test_output.stdout }}'
