---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/jailer --version
      register: jailer_test_output
    - name: jailer --version
      debug:
        msg: '{{ jailer_test_output.stdout }}'
    - command: /usr/local/bin/firecracker --version
      register: firecracker_test_output
    - name: firecracker --version
      debug:
        msg: '{{ firecracker_test_output.stdout }}'
    - command: /usr/local/bin/seccompiler-bin --version
      register: seccomp_bin_test_output
    - name: seccompiler-bin --version
      debug:
        msg: '{{ seccomp_bin_test_output.stdout }}'
