---
- name: Testing andrewrothstein.firecracker
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'jailer --version'
      ansible.builtin.command: jailer --version
      changed_when: false
      register: jailer_test_output
    - name: Output from 'jailer --version'
      ansible.builtin.debug:
        msg: '{{ jailer_test_output.stdout }}'
    - name: Executing 'firecracker --version'
      ansible.builtin.command: firecracker --version
      changed_when: false
      register: firecracker_test_output
    - name: Output from 'firecracker --version'
      ansible.builtin.debug:
        msg: '{{ firecracker_test_output.stdout }}'
    - name: Executing 'seccompiler-bin --version'
      ansible.builtin.command: seccompiler-bin --version
      changed_when: false
      register: seccomp_bin_test_output
    - name: Output from 'seccompiler-bin --version'
      ansible.builtin.debug:
        msg: '{{ seccomp_bin_test_output.stdout }}'
