---
- name: Mkdir {{ firecracker_parent_install_subdir }}
  become: true
  become_user: root
  ansible.builtin.file:
    path: '{{ firecracker_parent_install_subdir }}'
    state: directory
    mode: '755'
- name: Check for install in {{ firecracker_install_dir }}
  become: true
  ansible.builtin.stat:
    path: '{{ firecracker_install_dir }}'
  changed_when: false
  register: firecracker_binary
- name: Downloading and installing firecracker
  when: not firecracker_binary.stat.exists
  block:
    - name: Downloading {{ firecracker_url }} to {{ firecracker_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ firecracker_url }}'
        dest: '{{ firecracker_tmp_tgz }}'
        checksum: '{{ firecracker_checksum }}'
        mode: '644'
    - name: Installing andrewrothstein.unarchivedeps
      ansible.builtin.include_role:
        name: andrewrothstein.unarchivedeps
    - name: Unarchiving {{ firecracker_tmp_tgz }} to {{ firecracker_parent_install_subdir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ firecracker_tmp_tgz }}'
        dest: '{{ firecracker_parent_install_subdir }}'
        creates: '{{ firecracker_install_dir }}'
  always:
    - name: Rm {{ firecracker_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ firecracker_tmp_tgz }}'
        state: absent
- name: Linking executables in {{ firecracker_install_dir }} to {{ firecracker_parent_install_dir }}/bin
  become: true
  become_user: root
  with_items: '{{ firecracker_apps }}'
  ansible.builtin.file:
    src: '{{ firecracker_install_dir }}/{{ item }}-{{ firecracker_ver }}-{{ firecracker_arch }}'
    dest: '{{ firecracker_parent_install_dir }}/bin/{{ item }}'
    state: link
